CREATE TABLE IF NOT EXISTS users (
 id bigint generated by default as identity(start with 0) primary key,
 firstname varchar(64) not null,
 lastname varchar(64) not null,
 username varchar(255) not null,
 password varchar()255) not null,
 enabled boolean not null,

 created datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'time this record was created this will be used for message aging',
 update timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 who VARCHAR(100) DEFAULT 'script',
 comments VARCHAR(2048)
) 

create table authorities (
  id bigint generated by default as identity(start with 0) primary key,
  username varchar(255) not null,
  authority varchar_ignorecase(255) not null,
  constraint fk_authorities_users foreign key(username) references users(username),
   
  created datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'time this record was created this will be used for message aging',
  updated timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  who VARCHAR(100) DEFAULT 'script',
 comments VARCHAR(2048)
  );
  
create unique index ix_auth_username on authorities (username,authority);
  